import { useState } from 'react'
import { useGetResearchDefinitionsQuery, useGetMyResearchQuery, useStartResearchMutation } from '@/api/endpoints/researchApi'
import { usePrerequisites } from '@/hooks/usePrerequisites'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Planet } from '@/types/api.types'
import { formatNumber } from '@/lib/formatters'
import { toast } from 'sonner'
import { FlaskConical, CheckCircle, Lock, Loader2, AlertCircle } from 'lucide-react'
import { Skeleton } from '@/components/ui/skeleton'

interface ResearchTabProps {
  planet: Planet
}

export function ResearchTab({ planet }: ResearchTabProps) {
  const [startResearchDialogOpen, setStartResearchDialogOpen] = useState(false)
  const [selectedResearchSlug, setSelectedResearchSlug] = useState<string | null>(null)

  const { data: definitions, isLoading: isLoadingDefinitions } = useGetResearchDefinitionsQuery()
  const { data: researchProgress, isLoading: isLoadingProgress } = useGetMyResearchQuery()
  const [startResearch, { isLoading: isStarting }] = useStartResearchMutation()

  // Get all research definitions for prerequisite checking
  const allResearchDefinitions = definitions?.research || []
  const { canBuildItem } = usePrerequisites(Number(planet.id), allResearchDefinitions as unknown as any[])

  const handleStartResearch = async (researchSlug: string) => {
    try {
      await startResearch({ research_slug: researchSlug }).unwrap()
      toast.success('Research started successfully!')
      setStartResearchDialogOpen(false)
      setSelectedResearchSlug(null)
    } catch (error: any) {
      toast.error(error?.data?.message || 'Failed to start research')
    }
  }

  const getResearchDefinition = (slug: string) => {
    return definitions?.research?.find(r => r.slug === slug)
  }

  const isResearchCompleted = (slug: string) => {
    return researchProgress?.completed_research?.includes(slug) || false
  }

  const canResearch = (slug: string) => {
    const research = researchProgress?.available_research?.find(r => r.slug === slug)
    return research?.can_research || false
  }

  const getResearchCost = (slug: string) => {
    const def = getResearchDefinition(slug)
    return def?.cost_research_points || 0
  }

  if (isLoadingDefinitions || isLoadingProgress) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-32" />
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {[1, 2, 3, 4].map((i) => (
            <Skeleton key={i} className="h-64" />
          ))}
        </div>
      </div>
    )
  }

  const researchPoints = researchProgress?.research_points || 0
  const completedResearch = researchProgress?.completed_research || []
  const allAvailableResearch = researchProgress?.available_research || []
  const availableResearch = allAvailableResearch.filter(research => canBuildItem(research.slug))

  return (
    <div className="space-y-6">
      {/* Research Points */}
      <Card className="panel-glass border-purple/20">
        <CardContent className="pt-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-muted-foreground">Research Points</p>
              <p className="text-3xl font-mono glow-purple">
                {formatNumber(researchPoints)}
              </p>
            </div>
            <FlaskConical className="w-12 h-12 text-purple-400" />
          </div>
          <p className="text-sm text-muted-foreground mt-2">
            Research points are generated by research facilities and can be used to unlock new technologies.
          </p>
        </CardContent>
      </Card>

      {/* Completed Research */}
      {completedResearch.length > 0 && (
        <Card className="panel-glass border-green/20">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <CheckCircle className="w-5 h-5 text-green-400" />
              Completed Research ({completedResearch.length})
            </CardTitle>
            <CardDescription>
              Technologies you have already researched
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {completedResearch.map((slug) => {
                const research = getResearchDefinition(slug)
                if (!research) return null

                return (
                  <div key={slug} className="flex items-start gap-3 p-3 bg-green/10 rounded-lg border border-green/20">
                    <CheckCircle className="w-5 h-5 text-green-400 mt-0.5" />
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-1">
                        <h4 className="font-medium">{research.name}</h4>
                        <Badge variant="outline" className="bg-green-500/20 text-green-400 border-green-500/30">
                          Completed
                        </Badge>
                      </div>
                      <p className="text-sm text-muted-foreground mb-2">
                        {research.description}
                      </p>
                      {Object.keys(research.effects).length > 0 && (
                        <div className="text-xs text-green-400">
                          <strong>Effects:</strong>{' '}
                          {Object.entries(research.effects).map(([key, value]) => (
                            <span key={key}>
                              {key.replace(/_/g, ' ')}: {typeof value === 'number' && value < 1 ? `+${(value * 100).toFixed(0)}%` : `+${value}`}
                            </span>
                          )).join(', ')}
                        </div>
                      )}
                    </div>
                  </div>
                )
              })}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Available Research */}
      {availableResearch.length > 0 && (
        <Card className="panel-glass border-cyan/20">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <FlaskConical className="w-5 h-5 text-cyan-400" />
              Available Research ({availableResearch.length})
            </CardTitle>
            <CardDescription>
              Technologies you can research
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {availableResearch.map((research) => {
                const definition = getResearchDefinition(research.slug)
                if (!definition) return null

                const canAfford = researchPoints >= research.cost
                const prerequisitesMet = definition.prerequisites.every(prereq =>
                  completedResearch.includes(prereq)
                )

                return (
                  <Card
                    key={research.slug}
                    className={`panel-glass ${
                      research.can_research && canAfford && prerequisitesMet
                        ? 'border-cyan/20'
                        : 'border-muted/20 opacity-60'
                    }`}
                  >
                    <CardHeader>
                      <CardTitle className="flex items-center gap-2 text-lg">
                        <FlaskConical className="w-5 h-5 text-cyan-400" />
                        {research.name}
                      </CardTitle>
                      <CardDescription>
                        {definition.description}
                      </CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                      <div className="flex items-center justify-between">
                        <span className="text-sm text-muted-foreground">Cost</span>
                        <Badge variant="outline" className={canAfford ? 'text-purple-400' : 'text-destructive'}>
                          {formatNumber(research.cost)} RP
                        </Badge>
                      </div>

                      {definition.prerequisites.length > 0 && (
                        <div className="p-3 bg-muted/20 rounded-lg">
                          <p className="text-sm font-medium mb-2">Prerequisites:</p>
                          <div className="space-y-1">
                            {definition.prerequisites.map((prereq) => {
                              const isCompleted = completedResearch.includes(prereq)
                              const prereqDef = getResearchDefinition(prereq)
                              return (
                                <div key={prereq} className="flex items-center gap-2 text-sm">
                                  {isCompleted ? (
                                    <CheckCircle className="w-4 h-4 text-green-400" />
                                  ) : (
                                    <Lock className="w-4 h-4 text-muted-foreground" />
                                  )}
                                  <span className={isCompleted ? 'text-green-400' : 'text-muted-foreground'}>
                                    {prereqDef?.name || prereq}
                                  </span>
                                </div>
                              )
                            })}
                          </div>
                        </div>
                      )}

                      {Object.keys(definition.effects).length > 0 && (
                        <div className="p-3 bg-cyan/10 rounded-lg">
                          <p className="text-sm font-medium text-cyan-400 mb-1">Effects:</p>
                          <div className="space-y-1 text-sm">
                            {Object.entries(definition.effects).map(([key, value]) => (
                              <div key={key} className="flex justify-between">
                                <span>{key.replace(/_/g, ' ')}:</span>
                                <span className="text-green-400">
                                  {typeof value === 'number' && value < 1 ? `+${(value * 100).toFixed(0)}%` : `+${value}`}
                                </span>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}

                      {(!research.can_research || !canAfford || !prerequisitesMet) && (
                        <div className="flex items-center gap-2 p-3 bg-destructive/10 border border-destructive/20 rounded-lg">
                          <AlertCircle className="w-4 h-4 text-destructive" />
                          <span className="text-sm text-destructive">
                            {!prerequisitesMet
                              ? 'Prerequisites not met'
                              : !canAfford
                              ? 'Insufficient research points'
                              : 'Cannot research'}
                          </span>
                        </div>
                      )}

                      <Dialog>
                        <DialogTrigger asChild>
                          <Button
                            className="w-full"
                            disabled={!research.can_research || !canAfford || !prerequisitesMet}
                            onClick={() => setSelectedResearchSlug(research.slug)}
                          >
                            <FlaskConical className="w-4 h-4 mr-2" />
                            Start Research
                          </Button>
                        </DialogTrigger>
                        <DialogContent className="panel-glass border-purple/20">
                          <DialogHeader>
                            <DialogTitle>Start Research</DialogTitle>
                            <DialogDescription>
                              Are you sure you want to start researching {research.name}?
                            </DialogDescription>
                          </DialogHeader>
                          <div className="space-y-4">
                            <div className="p-4 bg-muted/20 rounded-lg">
                              <div className="space-y-2 text-sm">
                                <div className="flex justify-between">
                                  <span>Research Points Cost:</span>
                                  <span className="font-mono text-purple-400">
                                    {formatNumber(research.cost)} RP
                                  </span>
                                </div>
                                <div className="flex justify-between">
                                  <span>Current Research Points:</span>
                                  <span className={`font-mono ${
                                    researchPoints >= research.cost ? 'text-green-400' : 'text-destructive'
                                  }`}>
                                    {formatNumber(researchPoints)} RP
                                  </span>
                                </div>
                              </div>
                            </div>
                            <DialogFooter>
                              <Button
                                variant="outline"
                                onClick={() => {
                                  setStartResearchDialogOpen(false)
                                  setSelectedResearchSlug(null)
                                }}
                              >
                                Cancel
                              </Button>
                              <Button
                                onClick={() => handleStartResearch(research.slug)}
                                disabled={isStarting || !canAfford || !prerequisitesMet}
                              >
                                {isStarting ? (
                                  <>
                                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                                    Starting...
                                  </>
                                ) : (
                                  <>
                                    <FlaskConical className="w-4 h-4 mr-2" />
                                    Start Research
                                  </>
                                )}
                              </Button>
                            </DialogFooter>
                          </div>
                        </DialogContent>
                      </Dialog>
                    </CardContent>
                  </Card>
                )
              })}
            </div>
          </CardContent>
        </Card>
      )}

      {/* No Available Research */}
      {availableResearch.length === 0 && completedResearch.length === 0 && (
        <Card className="panel-glass border-muted/20">
          <CardContent className="pt-6 text-center">
            <FlaskConical className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
            <h3 className="text-lg font-semibold mb-2">No Research Available</h3>
            <p className="text-muted-foreground mb-4">
              Build research facilities to generate research points and unlock new technologies.
            </p>
          </CardContent>
        </Card>
      )}
    </div>
  )
}
